name: devfolio
description: devfolio migrated to jaspr from flutter.
version: 0.2.0

environment:
  sdk: ^3.8.0

dependencies:
  jaspr: ^0.22.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.10
  jaspr_builder: ^0.22.2
  jaspr_lints: ^0.6.0
  lints: ^6.1.0
  jaspr_test: ^0.22.2

  freezed: ^3.2.5
  json_serializable: ^6.7.1

jaspr:
  mode: static
